In [1]:
import numpy as np

In [4]:
N = 3
# 例としてすべて1になる配列を定義
a = np.ones([N, N])
x = np.ones(N)
b = np.ones(N)

# 前進消去
k = 0
i = k + 1
alpha = a[i,k] / a[k,k]
for j in range(k, N):
    a[i,j] = a[i,j] - alpha * a[k,j]
b[i] = b[i] - alpha * b[k]

In [ ]:
# 前進消去v2
k = 0
for i in range(k+1, N):
    alpha = a[i,k] / a[k,k]
    for j in range(k, N):
        a[i,j] = a[i,j] - alpha * a[k,j]
    b[i] = b[i] - alpha * b[k]

In [ ]:
# 前進消去v3
for k in range(N-1):
    for i in range(k+1, N):
        alpha = a[i,k] / a[k,k]
        for j in range(k, N):
            a[i,j] = a[i,j] - alpha * a[k,j]
        b[i] = b[i] - alpha * b[k]

In [82]:
# 例題11-1
N = 3
a = np.array([[2, 1, -1],
             [4, 3, 1],
             [1, -1, 2]]).astype(float)
b = np.array([2, 14, 7]).astype(float)
x = np.array([0, 0, 0])

In [83]:
# 前進消去v3
for k in range(N-1):
    for i in range(k+1, N):
        alpha = a[i,k] / a[k,k]
        for j in range(k, N):
            a[i,j] -= alpha * a[k,j]
        b[i] -= alpha * b[k]

In [84]:
a

array([[ 2.,  1., -1.],
       [ 0.,  1.,  3.],
       [ 0.,  0.,  7.]])

In [85]:
b

array([ 2., 10., 21.])

In [56]:
# 前進消去
for k in range(N-1):
    for i in range(k+1, N):
        alpha = a[i,k] / a[k,k]
        for j in range(k, N):
            a[i,j] -= alpha * a[k,j]
        b[i] -= alpha * b[k]
# 後退代入
x[N-1] = b[N-1] / a[N-1, N-1]
for i in range(N-2, -1, -1):
    bi = b[i]
    for k in range(i+1, N):
        bi -= a[i,k] * x[k]
    x[i] = bi / a[i,i]
x
    

array([2, 1, 3])

In [55]:
x

array([2, 1, 3])

# 例題11-3

In [74]:
N = 8
a = np.array([[1, 2, 1, 2, 1, 2, 1, 2],
             [2, 1, 1, 4, 1, 2, 1, 1],
             [1, 3, -1, 2, -1, 2, 1, -1],
             [3, -1, 1, -2, 3, 1, -1, 1],
             [2, 2, 2, 0, -1, 3, 1, 2],
             [4, -1, -1, -2, 3, 2, 0, 1],
             [1, 3, 0, 4, -2, -1, 1, 2],
             [2, -1, 1, 6, 3, 2, 1, -1]]).astype(float)
b = np.array([5, 8, -9, -1, 13, -12, 16, 5]).astype(float)
x = np.array([0, 0, 0, 0, 0, 0, 0, 0]).astype(float)
a[5,5]

2.0

In [76]:
# 前進消去
for k in range(N-1):
    for i in range(k+1, N):
        alpha = a[i,k] / a[k,k]
        for j in range(k, N):
            a[i,j] -= alpha * a[k,j]
        b[i] -= alpha * b[k]
# 後退代入
x[N-1] = b[N-1] / a[N-1, N-1]
for i in range(N-1, -1, -1):
    bi = b[i]
    for k in range(i+1, N):
        bi -= a[i,k] * x[k]
    x[i] = bi / a[i,i]
x
    

array([ 2. , -1. ,  7. ,  0.5, -2. , -4. ,  5. ,  1. ])

In [70]:
b

array([  5,  -2, -14, -11,   9,   4,  11,   3])